GET http://localhost:8080/securutymaterial?credential=graph_user
Cookie:JSESSIONID=DD908E56C3503178F3E3FCC7DC3F7506BD7FC27EC966792A0C28030DA3C1DC0C; BIGipServere2761tmnavrhcie.factory.customdomain=!Oxi5A4wRuqzb+/zLtYhPov1QD8O5hRcyQ90obGdoOBmZXNn2YQw2q8weXyZp9zhr/1F0y5a79QdPVM0=; slo_regular_domains_eu1_a1fc868e8_a1fc868e8=H4sIAAAAAAAAAAEwAM%2F%2FFjLFqmWK5ic2uFsZ1sY9%2BF6uJwNZyNm7YjrC8xzMbq8WOvtVzNBcK%2FrKmMKG%2Blm4Qb4A6jAAAAA%3D; JTENANTSESSIONID_a1fc868e8=2GUPMfQFNGesmecxKFnTGx9SJwxtTU3UTj%2F7iFCVqjY%3D; slo_regular_domains_eu1_a8f777579_a8f777579=H4sIAAAAAAAAAAEwAM%2F%2FqOfCRZUArNtsvZOMvW%2Bx3I1mSIWNE4RaVnqrTHynBNER%2FXC3poB94k0E6uWY3novJfcTGTAAAAA%3D; JTENANTSESSIONID_a8f777579=PUTzmEf0pzTuM2y42ASFeORhwCqOKFI9J19vIW1Plxk%3D
tenant:https://e2761-tmn.hci.eu1.hana.ondemand.com